---
label: default blogpost
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
- type: file
  name: banner
  label: banner
pages:
- content/blog/we-are-summit-kings.md
